%% Check patient-level CNN performance
% Date: 2025-10-10

%% Sanity-check stack-to-experiment mapping of autogenerated snapshots

stacks = "stacks_old.txt";

% b = build_statistics_v3(stacks);

stack_to_exp_mapping_autogen_snapshots_v1 = dictionary(1:16,[119 119 130 ...
    130 26 26 32 32 14 14 41 41 18 18 69 69]);

stack_to_exp_mapping_autogen_snapshots_v2 = dictionary(1:32, [repmat(119,1,4) ...
                                                repmat(130,1,4) repmat(26,1,4) ...
                                                repmat(32,1,4) repmat(14,1,4) ...
                                                repmat(41,1,4) repmat(18,1,4) ...
                                                repmat(69,1,4)]);

%% Load and classify data

load(['/Users/madsk418/UU Dropbox/Madeleine S/Simulation_and_invasion/comp/source/' ...
    'matlab/brainslice_manuscript_repo/Gliotrace_framework/trainedNetwork_6class_v2.mat'])

imds = imageDatastore('/Users/madsk418/Desktop/training_data_6class_v2/' ...
       ,"FileExtensions",'.tif', 'LabelSource','foldernames','IncludeSubfolders',true);

imds.ReadFcn = @customReadFunction;

classNames = categories(imds.Labels);

X = readall(imds);
probs = [];
embeddings_relu6 = [];
embeddings_fc2 = [];

% Get softmax probs and 256 embedding for each image in labelled data

for i=1:length(X)
    probs = [probs; trainedNetwork_6class_v2.predict(X{i})];
    feature_embedding = predict(trainedNetwork_6class_v2,X{i},'Outputs', 'relu6');
    embeddings_relu6 = [embeddings_relu6; feature_embedding];
    embeddings_fc2 = [embeddings_fc2; predict(trainedNetwork_6class_v2,X{i},'Outputs', 'fc2')];
    i
end


%%

trueLabels = imds.Labels;

metadata=readtable('/Volumes/MyGroups$/Iron/konfokalmikroskop/Hitesh Montage and Overlays/hitesh_metadata.xlsx');

patlabs = categorical([]);

for i=1:length(imds.Files)
    % Convert to numeric if needed
    try
        expid = str2double(regexp(imds.Files{i}, 'exp(\d{3})', 'tokens', 'once'));
        try
            hgcc = metadata.HGCC{expid};
        catch
            expid = str2double(regexp(imds.Files{i}, 'exp(\d{2})', 'tokens', 'once'));
            hgcc = metadata.HGCC{expid};
        end
        hgcc = categorical(cellstr(hgcc(1:7)));
        patlabs(i) = hgcc;
    catch
        if(contains(imds.Files{i}, "score"))
            expr = '(?<=stack_)\d+';
            stackid = regexp(imds.Files{i}, expr, 'match');
            expid = stack_to_exp_mapping_autogen_snapshots_v2(str2num(stackid{:}));
            hgcc = metadata.HGCC{expid};
            hgcc = categorical(cellstr(hgcc(1:7)));
            patlabs(i) = hgcc;
        else
            expr = '(?<=stack_)\d+';
            stackid = regexp(imds.Files{i}, expr, 'match');
            try
                expid = stack_to_exp_mapping_autogen_snapshots_v1(str2num(stackid{:}));
                hgcc = metadata.HGCC{expid};
                hgcc = categorical(cellstr(hgcc(1:7)));
                patlabs(i) = hgcc;
            catch
                patlabs(i) = categorical(NaN);
            end
        end
    end
    i
end

%%
[coeff, score, ~, ~, explained] = pca(embeddings_relu6);

% score(:,1:2) are the first 2 principal components
figure;
gscatter(score(:,1), score(:,2), patlabs);
xlabel(['PC1 (' num2str(explained(1), '%.1f') '%)']);
ylabel(['PC2 (' num2str(explained(2), '%.1f') '%)']);
title('PCA projection of 256-D features');

%%

[coeff, score, ~, ~, explained] = pca(embeddings_relu6);

% score(:,1:2) are the first 2 principal components
figure;
gscatter(score(:,1), score(:,2), trueLabels);
xlabel(['PC1 (' num2str(explained(1), '%.1f') '%)']);
ylabel(['PC2 (' num2str(explained(2), '%.1f') '%)']);
title('PCA projection of 256-D features');

%%

predictedLabels = onehotdecode(probs,classNames,2);
trueLabels = imds.Labels;

error_rates = [];

pat = unique(patlabs');
pat = pat(1:5);

for i=1:5
    idx = (patlabs == pat(i))';
    confmat = confusionmat(trueLabels(idx), predictedLabels(idx));
    accuracy = sum(diag(confmat)) / sum(confmat(:));
    error_rates(i) = 1-accuracy;
    i
end

%% Check patient-specific accuracy on unseen data
 
[fold1, fold2, fold3, fold4, fold5, fold6, fold7, fold8, fold9, fold10] = splitEachLabel(imds,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1);
            
folds = {fold1.Files, fold2.Files, fold3.Files, fold4.Files, fold5.Files, fold6.Files, fold7.Files, fold8.Files, fold9.Files, fold10.Files};

fold_indices = [1:8, 9, 10;
                2:9, 10, 1;
                3:10, 1, 2;
                [4:10 1], 2, 3;
                [5:10 1:2], 3, 4;
                [6:10 1:3], 4, 5;
                [7:10 1:4], 5, 6;
                [8:10 1:5], 6, 7;
                [9:10 1:6], 7, 8;
                [10 1:7], 8, 9];


i=1;

% Test data that the current NN hasn't seen
imdsTest = imageDatastore(folds{fold_indices(i, 10)}, "IncludeSubfolders",true, "LabelSource","foldernames");

imdsTest.ReadFcn = @customReadFunction5;

trueLabels = imdsTest.Labels;

% Evaluate on test set
X = readall(imdsTest);
probs = [];

[tf, idx] = ismember(folds{fold_indices(i, 10)}, imds.Files);

patlabs_test = patlabs(idx);

for m=1:length(X)
    probs = [probs; trainedNetwork_6class_v2.predict(X{m})];
    m
end    

predictedLabels = onehotdecode(probs,classNames,2);

error_rates = [];

pat = unique(patlabs_test');

for i=1:length(pat)
    idx = (patlabs_test == pat(i))';
    confmat = confusionmat(trueLabels(idx), predictedLabels(idx));
    accuracy = sum(diag(confmat)) / sum(confmat(:));
    error_rates(i) = 1-accuracy;
    i
end


